name: null
favicon: null
layout_spectrum: 0.03248
typography_spectrum: 0.02371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1a20'
    - '#4da1fc'
    - '#b52d55'
    - '#cc8634'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: null
    url: null
