name: null
favicon: null
layout_spectrum: 0.108
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e9ec'
    - '#000000'
    - '#b1b3b2'
    - '#484848'
    - '#d9601b'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
